on:
  pull_request:
    branches:
      - main
      - master
  push: 
    branches: 
      - main
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses : actions/setup-java@v2
        with: 
          java-versions: '12.x'
      - uses: subosito/flutter-action@v2
         with:
          flutter-version: '2.5.3'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release --split-per-abi
      - name: Push to Release
        uses: ncipollo/release-action@v2
        with: 
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.1+${{ github.run_number }}
          token: ${{ secrets.TOKEN }}



#push to main,master
#pull request on main and master